# Generated by Django 4.2.6 on 2023-10-31 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvento', models.IntegerField()),
                ('nomeEvento', models.CharField(max_length=100)),
                ('dataEvento', models.DateField()),
                ('localEvento', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFuncao', models.IntegerField()),
                ('nomeFuncao', models.CharField(max_length=50)),
                ('descricaoFuncao', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMembro', models.IntegerField()),
                ('nomeMembro', models.CharField(max_length=150)),
                ('enderecoMembro', models.CharField(max_length=200)),
                ('telefoneMembro', models.CharField(max_length=11)),
                ('dataNascimentoMembro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoInstrumento', models.IntegerField()),
                ('nomeTipoInstrumento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVisita', models.IntegerField()),
                ('localVisita', models.CharField(max_length=200)),
                ('dataVisita', models.DateField()),
                ('anfitriaoVisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membro')),
            ],
        ),
        migrations.CreateModel(
            name='PequenoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFuncao', models.IntegerField()),
                ('nomePequenoGrupo', models.CharField(max_length=100)),
                ('localPequenoGrupo', models.CharField(max_length=200)),
                ('liderPequenoGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMinisterio', models.IntegerField()),
                ('nomeMinisterio', models.CharField(max_length=50)),
                ('descricaoMinisterio', models.CharField(max_length=300)),
                ('liderMinisterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idInstrumento', models.IntegerField()),
                ('nomeInstrumento', models.CharField(max_length=50)),
                ('instrumentistaInstrumento', models.ManyToManyField(to='app.membro')),
                ('tipoInstrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoinstrumento')),
            ],
        ),
    ]
