# Generated by Django 4.2.6 on 2023-11-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministerio',
            name='membrosMinisterio',
            field=models.ManyToManyField(related_name='ministerios', to='app.membro'),
        ),
        migrations.AlterField(
            model_name='ministerio',
            name='liderMinisterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lider_ministerio', to='app.membro'),
        ),
    ]
