# Generated by Django 4.2.6 on 2023-11-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ministerio_membrosministerio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pequenogrupo',
            old_name='idFuncao',
            new_name='idPequenoGrupo',
        ),
        migrations.AddField(
            model_name='funcao',
            name='membroFuncao',
            field=models.ManyToManyField(related_name='funcoes', to='app.membro'),
        ),
        migrations.AddField(
            model_name='pequenogrupo',
            name='membrosPequenoGrupo',
            field=models.ManyToManyField(related_name='pequenos_grupos', to='app.membro'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='instrumentistaInstrumento',
            field=models.ManyToManyField(related_name='instrumentos', to='app.membro'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='anfitriaoVisita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_anfitriao', to='app.membro'),
        ),
    ]
