# Generated by Django 4.2.6 on 2023-11-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_idfuncao_pequenogrupo_idpequenogrupo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='funcao',
            name='idFuncao',
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='idInstrumento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='idMembro',
        ),
        migrations.RemoveField(
            model_name='ministerio',
            name='idMinisterio',
        ),
        migrations.RemoveField(
            model_name='pequenogrupo',
            name='idPequenoGrupo',
        ),
        migrations.RemoveField(
            model_name='tipoinstrumento',
            name='idTipoInstrumento',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='idVisita',
        ),
    ]
